version: '3.8'

services:
  cryptotoolkit-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=info
      - CRYPTO_EXPLAIN_MODE=true
    volumes:
      - ./configs:/root/configs:ro
    command: ["./cryptotoolkit-api"]

  cryptotoolkit-cli:
    build: .
    volumes:
      - ./configs:/root/configs:ro
    command: ["./cryptotoolkit", "--help"]
    profiles:
      - cli

networks:
  default:
    name: cryptotoolkit-network
