# CryptoToolkit-Go Configuration

server:
  host: localhost
  port: 8080

database:
  type: memory
  url: ""

crypto:
  default_key_size: 2048
  explain_mode: false

logging:
  level: info
  format: json
